apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: purple-mermaid-app3-devfile-sample-ryok-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: purple-mermaid-app3-devfile-sample-ryok-sample
    app.kubernetes.io/part-of: purple-mermaid-app3
  name: purple-mermaid-app3-devfile-sample-ryok-sample
  namespace: abhindas-tenant
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: purple-mermaid-app3-devfile-sample-ryok-sample
    weight: 100
status: {}
