apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: purple-mermaid-app3-devfile-sample-ryok-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: purple-mermaid-app3-devfile-sample-ryok-sample
    app.kubernetes.io/part-of: purple-mermaid-app3
  name: purple-mermaid-app3-devfile-sample-ryok-sample
  namespace: abhindas-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: purple-mermaid-app3-devfile-sample-ryok-sample
status:
  loadBalancer: {}
