apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-4key
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-4key
    app.kubernetes.io/part-of: purple-mermaid-app3
  name: devfile-sample-4key
  namespace: abhindas-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-4key
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-4key
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:abhindas-tenant-devfile-sample-4key
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
